### ISSUE TITLE
no source code

### ISSUE THREAD

**Issue by landorg** [soulsbysynths/SsAtmStrings#1]
new atmegatron owner here looking for the source code
:eyes:

**Comment by soulsbysynths** [comment]
The project folders are just containers for the Arduino / Atmel Studio project files.  Nearly all the actual source code is in the   [Libraries](https://github.com/soulsbysynths/libraries). Check out the Strings and Strings Engine folders for the Strings firmware.

**Comment by landorg** [comment]
Ah there. Thanks :D
